//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopHighPos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSalesBasket
    {
        public int Id { get; set; }
        public Nullable<System.Guid> basketid { get; set; }
        public Nullable<int> proid { get; set; }
        public string product { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> cost { get; set; }
    }
}
