//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopHighPos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSalesOrderDetail
    {
        public int oderdetailsid { get; set; }
        public Nullable<System.Guid> odernumber { get; set; }
        public string product { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> salesprice { get; set; }
        public Nullable<double> unitcost { get; set; }
        public Nullable<double> totals { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> lastupdateddate { get; set; }
    
        public virtual CashSalesOder CashSalesOder { get; set; }
    }
}
