//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopHighPos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDBEntities : DbContext
    {
        public POSDBEntities()
            : base("name=POSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CashSalesBasket> CashSalesBaskets { get; set; }
        public virtual DbSet<CashSalesOder> CashSalesOders { get; set; }
        public virtual DbSet<CashSalesOrderDetail> CashSalesOrderDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<JournalVoucher> JournalVouchers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Producthistory> Producthistories { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CreditSalesOder> CreditSalesOders { get; set; }
        public virtual DbSet<CreditSalesOrderDetail> CreditSalesOrderDetails { get; set; }
        public virtual DbSet<CreditStatement> CreditStatements { get; set; }
    }
}
